import React from 'react'

import '../Assests/css/TermsAndCondition.css'

const TermsAndConditions = () => {
  return (
    <div>
      <div className="tac-container">
        <h2>Terms And Condition</h2>
        <h1>Monitoring</h1>
        <p>Merniverse has the right, but not the obligation, to monitor the content of this website, to determine compliance with these Terms of Use and any other operating rules established by Merniverse. Merniverse has the right in our sole discretion to edit, refuse to post or remove any material submitted to or posted on this website that we find to be in violation of these Terms of Use or is otherwise objectionable. You are solely responsible for any information you post, transmit or otherwise make available on this website. You acknowledge and agree that Merniverse does not have any liability for any action or inaction with respect to any conduct, communication or posting on this website.</p>

        <h1>Rights in Content</h1>
        <p>By displaying, publishing and making available for download and use by others any content, messages, text, files, images, photos, video, sounds, profiles, works of authorship, or any other materials ("Content") you give Merniverse a perpetual, irrevocable, worldwide, royalty-free, and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display and distribute any Content which you submit, post or display on or through the web site. You agree that this license includes a right for Merniverse to make such Content available to other companies, organizations or individuals with whom Merniverse has relationships for the provision of services, and to use such Content in connection with the provision of those services. You understand that Merniverse may (a) transmit or distribute your Content over various public networks and in various media; and (b) make such changes to your Content as are necessary to conform and adapt that Content to the technical requirements of connecting networks, devices, services or media. You agree that this license shall permit Merniverse to take these actions. You confirm and warrant to Merniverse that you have all the rights, power and authority necessary to grant the above license.</p>

        <h1>Machine Translation Disclaimer</h1>
        <p>Pages on this website, including product manuals and documentation, may have been translated using artificial intelligence or machine translation. Merniverse does not guarantee the accuracy of the translation and accepts no liability for possible errors. Any discrepancies or differences created in the translation are not binding and have no legal effect for compliance or enforcement purposes.</p>

        <h1>Disclaimer</h1>
        <p>THIS WEBSITE AND ALL CONTENT, MATERIALS, INFORMATION, SOFTWARE, PRODUCTS AND SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. YOUR USE OF THIS WEBSITE IS AT YOUR OWN RISK. Merniverse MAKES NO WARRANTIES OR REPRESENTATIONS, EXPRESS OR IMPLIED, AS TO THE FUNCTIONALITY OR USEFULNESS OF THIS WEBSITE OR ANY CONTENT. Merniverse DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Merniverse MAKES NO WARRANTY THAT, (I) THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (II) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE OR RELIABLE, (III) THE QUALITY OF ANY PRODUCTS, SERVICES, CONTENT, INFORMATION, OR OTHER MATERIALS PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE WILL MEET YOUR EXPECTATIONS, (IV) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED, OR THAT THIS WEBSITE, ITS CONTENT, AND THE SERVER ON WHICH THE WEBSITE AND CONTENT ARE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. ANY MATERIAL (INCLUDING CONTENT) DOWNLOADED OR OBTAINED THROUGH THE USE OF THIS WEBSITE IS DONE AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY MATERIAL. INFORMATION CREATED BY THIRD PARTIES THAT YOU MAY ACCESS ON THIS WEBSITE OR THROUGH LINKS IS NOT ADOPTED OR ENDORSED BY Merniverse AND REMAINS THE RESPONSIBILITY OF THE THIRD PARTY.</p>
      
        <h1>Limitation of Liability</h1>
        <p>TO THE FULLEST EXTENT PERMITTED BY LAW, Merniverse IS NOT LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES (INCLUDING, WITHOUT LIMITATION, LOSS OF BUSINESS, REVENUE, PROFITS, GOODWILL, USE, DATA, ELECTRONICALLY TRANSMITTED ORDERS, OR OTHER ECONOMIC ADVANTAGE) ARISING OUT OF OR IN CONNECTION WITH THE WEBSITE, EVEN IF Merniverse HAS PREVIOUSLY BEEN ADVISED OF, OR REASONABLY COULD HAVE FORESEEN, THE POSSIBILITY OF SUCH DAMAGES, HOWEVER THEY ARISE, WHETHER IN BREACH OF CONTRACT OR IN TORT (INCLUDING NEGLIGENCE), INCLUDING WITHOUT LIMITATION DAMAGES DUE TO (a) THE USE OF OR THE INABILITY TO USE THE WEBSITE; (b) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES RESULTING FROM ANY GOODS, DATA, INFORMATION OR SERVICES PURCHASED OR OBTAINED OR MESSAGES RECEIVED OR TRANSACTIONS ENTERED INTO, THROUGH OR FROM THE WEBSITE; (c) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE WEBSITE, INCLUDING WITHOUT LIMITATION UNAUTHORIZED ACCESS TO OR ALTERATION OF TRANSMISSIONS OR DATA, MALICIOUS OR CRIMINAL BEHAVIOR, OR FALSE OR FRAUDULENT TRANSACTIONS, OR (d) CONTENT OR INFORMATION YOU MAY DOWNLOAD, USE, MODIFY OR DISTRIBUTE. NOTWITHSTANDING ANY OTHER CLAUSE IN THIS AGREEMENT, Merniverse'S TOTAL AGGREGATE LIABILITY, REGARDLESS OF THE FORM OF THE CAUSE OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING WITHOUT LIMITATION NEGLIGENCE), STATUTE OR OTHERWISE, AND YOUR SOLE AND EXCLUSIVE REMEDY, SHALL BE LIMITED TO PROVEN DIRECT DAMAGES CAUSED BY Merniverse IN AN AMOUNT NOT TO EXCEED FIVE HUNDRED DOLLARS (US $500.00). THE PROVISIONS OF THIS SECTION ALLOCATE RISKS UNDER THESE TERMS OF USE BETWEEN Merniverse AND YOU. THE FOREGOING LIMITATIONS, EXCLUSIONS AND DISCLAIMERS APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, EVEN IF ANY REMEDY FAILS IN ITS ESSENTIAL PURPOSE. TO THE EXTENT ANY JURISDICTION DOES NOT ALLOW THE EXCLUSION OR LIMITATION OF DIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES, PORTIONS OF THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY.</p>
      
        <h2>Privacy Policy</h2>
        <p>Merniverse, Inc. is committed to protecting your privacy. We have prepared this Privacy Policy to describe to you our practices regarding the Personal Data (as defined below) we collect from users of our website located at Merniverse.com and in connection with our Merniverse products and services (the "Products"). In addition, this Privacy Policy tells you about your privacy rights and how the law protects you. This website and our Products are not intended for children and we do not knowingly collect data relating to children. It is important that you read this Privacy Policy together with any other privacy notice or fair processing notice we may provide on specific occasions when we are collecting or processing Personal Data about you so that you are fully aware of how and why we are using your data. This Privacy Policy supplements the other notices and is not intended to override them.</p>
      </div>
    </div>
  )
}

export default TermsAndConditions
